// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bjc4BBP9zzI7Cwlj1LWs5etU59CKTng',
    appId: '1:83035466479:web:2510fa491ff7181f1f491a',
    messagingSenderId: '83035466479',
    projectId: 'textit-chat-app-96251',
    authDomain: 'textit-chat-app-96251.firebaseapp.com',
    storageBucket: 'textit-chat-app-96251.appspot.com',
    measurementId: 'G-JZS266KLT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2FxqjqL2ixVYmpl1al0upwCIe1P1dpU',
    appId: '1:83035466479:android:322586398546f7851f491a',
    messagingSenderId: '83035466479',
    projectId: 'textit-chat-app-96251',
    storageBucket: 'textit-chat-app-96251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSnCC6dJ4tfswaZoOxhrrrMGcywITLKYk',
    appId: '1:83035466479:ios:15273e1a3e8594e91f491a',
    messagingSenderId: '83035466479',
    projectId: 'textit-chat-app-96251',
    storageBucket: 'textit-chat-app-96251.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSnCC6dJ4tfswaZoOxhrrrMGcywITLKYk',
    appId: '1:83035466479:ios:b678871fb5e947dd1f491a',
    messagingSenderId: '83035466479',
    projectId: 'textit-chat-app-96251',
    storageBucket: 'textit-chat-app-96251.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
